# total_connect_client packaging file

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta:__legacy__"

[project]
name="total_connect_client"
version="2022.12"
authors = [
  { name="Craig J. Midwinter", email="craig.j.midwinter@gmail.com" },
]
description="Interact with Total Connect 2 alarm systems"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
keywords=["alarm", "TotalConnect"]
dependencies=["zeep>=4.1.0"]

[project.urls]
"Homepage" = "https://github.com/craigjmidwinter/total-connect-client"
"Bug Tracker" = "https://github.com/craigjmidwinter/total-connect-client/issues"

[tool.pylint."messages control"]
disable = ["use-symbolic-message-instead", "too-few-public-methods", "too-many-instance-attributes", "logging-fstring-interpolation", "missing-function-docstring", "missing-class-docstring", "protected-access", "line-too-long", "duplicate-code"]
